config/routes.rb
Rails.application.routes.draw do

  root 'posts#home'
  
  get 'signin' => 'sessions#new', as: 'signin'
  post 'sessions' => 'sessions#create', as: 'sessions'
  get 'signout' => 'sessions#destroy', as: 'signout'
  
  get 'signup' => 'users#new', as: 'signup'
  
  get '/authors' => 'users#authors', as: 'authors'
  
  get '/messages/:id/view' => 'messages#view', as: 'view_message'
  
  resources :users
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  
  resources :messages

end

app/models/user.rb
require 'carrierwave'
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments
  has_many :messages
  
  mount_uploader :avatar, ImageUploader
  
  before_save {|user| user.email = user.email.downcase if user.email}
  
  VALID_EMAIL_REGEX = /\A.+@.+\z/i
  
  validates :name,                  presence: true
  validates :email,                 presence: true,
                                    format: {with: VALID_EMAIL_REGEX},
                                    uniqueness: {case_sensitive: false}
  validates :password,              presence: true, on:[:new, :create]
  validates :password_confirmation, presence: true, on:[:new, :create]

  def full_name
    fname + ' ' + lname
  end
  
  scope :authors, -> { where(author: true) }
  scope :registered, -> { where("email IS NOT NULL") }
end

# A user has a list of responses. So comments must have a recipient_id (or access .commentable.user_id somehow?)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :redirect_incorrect_users, only: [:edit, :update, :destroy]

  def index
    @users = User.registered
  end
  
  def authors
    @authors = User.authors
  end

  def show
    @recent_posts = Post.where(user_id: current_user.id).limit(5)
    @recent_comments = Comment.where(user_id: current_user.id).limit(5)
    @messages = Message.where(recipient_id: current_user.id).where(viewed: false)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by(uuid: current_user.uuid)
    
    if @user.update(user_params)
      sign_in @user
      flash[:success] = "Your profile has been created successfully."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your profile has been updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email,:name,:phone_number,:avatar,:password,:password_confirmation,:description)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def redirect_incorrect_users
    if @user != current_user
      redirect_to current_user
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<ul class="no-list-style">
  <% users.each do |user| %>
    <li class="row">
      <div class="avatar">
        <%= image_tag user.avatar_url(:thumb) %>
      </div>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/authors.html.erb
<h1>Our Authors</h1>
<%= render 'users', users: @authors %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for @user, multipart: true do |f| %>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  
  <%= f.label :phone_number %><br>
  <%= f.text_field :phone_number %><br>
  
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %><br>
  
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  
  <%= f.submit 'Update!' %>
<% end %>

app/views/users/index.html.erb
<h1>Our Community</h1>
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, multipart: true do |f| %>
  <%= f.label :email %>*<br>
  <%= f.email_field :email %><br>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  
  <%= f.label :phone_number %><br>
  <%= f.text_field :phone_number %><br>
  
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %><br>
  
  <%= f.label :password %>*<br>
  <%= f.password_field :password %><br>
  
  <%= f.label :password_confirmation %>*<br>
  <%= f.password_field :password_confirmation %><br>
  
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  
  <%= f.submit 'Sign Up!' %>
<% end %>

app/views/users/show.html.erb
<h1>
  <%= @user.name + '\'s' %> Profile 
  <% if @user.uuid == current_user.uuid %>
    | <%= link_to 'Edit', edit_user_path(@user) %>
  <% end %>
</h1>

<div class="row">
  <div class="avatar avatar-lg left">
    <% if @user.avatar_url() %>
      <%= image_tag @user.avatar_url(:medium) %>
    <% end %>
  </div>
  <div>
    <p class="left">
      <% if @user == current_user %>
      Email: <%= @user.email %><br>
      Name: <%= @user.name %><br>
      Phone number: <%= number_to_phone(@user.phone_number, area_code: true) %><br>
      <% end %>
      About me: <%= @user.description %>
    </p>
  </div>
</div><br>

<% if current_user == @user %>
<div class="row">
  <section class="col">
    <h3>Responses</h3>
    <ul class="no-list-style indent">
      <% @messages.each do |message| %>
        <li name="<%= message.id %>">
          <%= markdown(message.body) %>
        </li>
      <% end %>
    </ul>
  </section>

  <% if @user.author %>
    <section class="col">
      <h3>Recent Posts</h3>
      <ul class="no-list-style indent">
        <% @recent_posts.each do |post| %>
          <li>
            <%= link_to post.heading, post %>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <section class="col">
    <h3>Recent Comments</h3>
    <ul class="no-list-style indent">
      <% @recent_comments.each do |comment| %>
        <li>
          <%= comment.body %> <%= link_to "(See post)", comment.post %>
        </li>
      <% end %>
    </ul>
  </section>
</div>
<% end %>