config/routes.rb
Rails.application.routes.draw do

  root 'posts#home'
  
  get 'signin' => 'sessions#new', as: 'signin'
  post 'sessions' => 'sessions#create', as: 'sessions'
  get 'signout' => 'sessions#destroy', as: 'signout'
  
  get 'signup' => 'users#new', as: 'signup'
  
  get '/authors' => 'users#authors', as: 'authors'
  
  get '/messages/:id/view' => 'messages#view', as: 'view_message'
  
  resources :users
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  
  resources :messages

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable

  validates :user_id, presence: true
  validates :heading, presence: true
  validates :body,    presence: true
  
  default_scope {order('created_at DESC')}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_emails, only: [:home, :index]
  before_action :prepare_commenting, only: [:home, :index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :redirect_incorect_user, only: [:edit, :update, :destroy]
  
  def home
    @posts = Post.limit(3)
    @recent_posts = Post.offset(3).limit(10)
  end
  
  def index
    @posts = Post.all
  end

  def show
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end
  
  def destroy
  end
  
  private
  
  def post_params
    params.require(:post).permit(:heading,:body)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def prepare_commenting
    @post
  end
  
  def check_emails
    @emails = []
    Gmail.connect(Rails.application.secrets.gmail_username, Rails.application.secrets.gmail_password) do |gmail|
      gmail.inbox.find(:unread).each do |email|
        email.read!
        if email.subject =~ /SMS/ or email.subject =~ /voicemail/
          @emails << email
        end
      end
    end
    
    process_emails(@emails)
  end
  
  def process_emails(emails)
    emails.each do |email|
      author = email.from[0].name.chomp
      subject = email.subject.chomp
      number = subject.gsub(/\D/, '')
      if number.length == 10
        @user = User.find_by(phone_number: number)
        if @user && @user.author
          body = email.body.decoded.gsub(/[\w\W]*Content-Type:\stext\/plain.*?\n\n/, '').gsub(/\n\n--[\w\W]*--/, '').chomp
          heading, body = body.split('*body*')
          
          @post = Post.create(heading: heading, body: body, user_id: @user.id)
        end
      end
    end
  end
  
  def redirect_incorect_user
    if current_user == @post.user
      return
    end
    redirect_to @post
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="avatar">
  <% if comment.user.avatar_url %>
    <%= image_tag comment.user.avatar_url(:thumb) %>
  <% else %>
    <%= image_tag 'default-avatar.png' %>
  <% end %>
</div>
<a name="comment-<%= comment.id %>"></a>
<div class="comment-main">
  <%= hidden_field_tag :comment_id, comment.id, class: 'comment_id' %>
  <%= link_to comment.user.name, comment.user, class: 'primary-color' %>&nbsp;-&nbsp;<%= timeago(comment.created_at) %><br>
  <p class="comment-body no-indent">
    <%= comment.body %>
  </p>
  <div class="comment-options">
    <%= link_to 'Reply', '#', class: 'grey reply' %>
  </div>
  
  <ul class="replies no-list-style">
    <% comment.comments.each do |reply| %>
      <li class="row">
        <%= render 'comment', comment: reply %>
      </li>
    <% end %>
  </ul>
</div>

<!--"$(this).parent().parent().parent().parent().find('.replies').prepend(\"<li><div class='avatar'><%# if signed_in? %><%#= image_tag current_user.avatar_url(:thumb) %><%# else %><%#= image_tag 'default-avatar.png' %><%# end %></div><div class='comment-main flex'><%#= form_for Comment.new do |f| %><%#= hidden_field_tag :comment_id, comment.id %><%#= f.text_area :body, placeholder: 'Join the discussion...', class: 'boxsizing-border' %><%#= f.submit 'Go! >>', class: 'left' %><%# end %></ul></div></li>\");"-->

app/views/posts/_comments.html.erb
<section class="comments">
  <% if hidden %>
    <%= link_to 'Show Comments', '#', class: 'comments-toggle' %>
    <div class="collapse uncollapse">
  <% end %>
    <h2>Comments</h2>
    <ul class="no-list-style">
      <li class="row">
        <div class="avatar">
          <% if signed_in? %>
            <%= image_tag current_user.avatar_url(:thumb) %>
          <% else %>
            <%= image_tag 'default-avatar.png' %>
          <% end %>
        </div>
        <div class="comment-main flex">
          <%= form_for Comment.new do |f| %>
            <%= hidden_field_tag :post_id, post.id %>
            
            <%= f.text_area :body, placeholder: "Join the discussion...", class: 'boxsizing-border flex', style: "display: block;" %>
            
            <%= f.submit 'Go! >>' %>
          <% end %>
        </div>
      </li>
      <% post.comments.each do |comment| %>
        <li class="row">
          <%= render 'comment', comment: comment %>
        </li>
      <% end %>
    </ul>
    
    <script type="text/javascript">
      $('a.reply').click(function(evt) {
        evt.preventDefault();
        var comment_id = $(this).parent().parent().find('.comment_id').attr('value');
        var data = "<%= escape_javascript(render :partial => 'comments/reply') %>";
        $($(this).parent().parent().find('.replies')[0]).prepend(data);
        $($(this).parent().parent().find('.replies')[0]).find('input[name="comment_id"]').attr('value', comment_id);
      });
    </script>
  <% if hidden %>
    </div>
  <% end %>
</section>

app/views/posts/_comments.js.erb
$(document).on("ready page:load", function() {
  $('a.reply').click(function(evt) {
    evt.preventDefault();
    var comment_id = $(this).parent().parent().find('.comment_id').attr('value')
    var token = $("meta[name='csrf-token']").attr("content");
    //var data = '<li class="row"><div class="avatar"><%# if signed_in? %><%#= image_tag current_user.avatar_url(:thumb) %><%# else %><%#= image_tag "default-avatar.png" %><%# end %></div><div class="comment-main flex"><form action="<%= comments_path %>" method="post" accept-charset="UTF-8"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="'+token+'" /><input type="hidden" name="comment_id" value="'+comment_id+'"><textarea placeholder="Join the discussion..." class="boxsizing-border" name="comment[body]" id="comment_body"></textarea><%#= submit_tag "Go! >>", class: "left" %></form></ul></div></li>';
    var data = "<%= escape_javascript(render :partial => 'comments/reply') %>";
    $($(this).parent().parent().find('.replies')[0]).prepend(data);
  });
});

app/views/posts/_post.html.erb
<article class="clearfix">
  <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
  <h1><%= post.heading %></h1>
  <div class="author-byline">
    <span>By <%= link_to post.user.name, post.user %></span>
  </div>
  <p><%= markdown(post.body) %></p>
  <div class="about-author">
    <h3 class="mobile-hide">About the Author</h3>
    <div class="avatar">
      <%= image_tag post.user.avatar_url(:small) %>
    </div>
    <p class="no-indent"><%= link_to post.user.name, post.user %><span class="mobile-hide"> - <%= post.user.description %></span></p>
  </div>
  <% if !comments_hidden.nil? and comments_hidden %>
    <%= render 'comments', post: post, hidden: true %>
  <% else %>
    <%= render 'comments', post: post, hidden: false %>
  <% end %>
</article>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
  <%= f.label :heading %><br>
  <%= f.text_field :heading %><br>
  
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  
  <%= f.submit 'Post!' %>
<% end %>

<script>
  var simplemde = new SimpleMDE({ element: $("#edit_post")[0] });
</script>

app/views/posts/home.html.erb
<ul class="posts no-list-style">
  <% @posts.each do |post| %>
    <li>
      <%= render 'post', post: post, comments_hidden: true %>
    </li>
  <% end %>
</ul>

<% content_for :aside do %>
  <aside id="aside-main">
    <h2>Latest Posts</h2>
    <ul class="no-list-style">
      <% @recent_posts.each do |post| %>
        <li>
          <%= link_to post do %><h3><%= post.heading %></h3><% end %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

app/views/posts/index.html.erb
<ul class="posts no-list-style">
  <% @posts.each do |post| %>
    <li>
      <%= render 'post', post: post, comments_hidden: true %>
      <!--<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
      <%= link_to post do %>
        <h2><%= post.heading %></h2>
      <% end %>
      <p class="indent">By <%= link_to post.user.name, post.user %></p>-->
    </li>
  <% end %>
</ul>

<% if current_user.author %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <%= f.label :heading %><br>
  <%= f.text_field :heading %><br>
  
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  
  <%= f.submit 'Post!' %>
<% end %>

<script>
  var simplemde = new SimpleMDE({ element: $("#new_post")[0] });
</script>

app/views/posts/show.html.erb
<%= render 'post', post: @post, comments_hidden: false %>