config/routes.rb
Rails.application.routes.draw do

  root 'posts#home'
  
  get 'signin' => 'sessions#new', as: 'signin'
  post 'sessions' => 'sessions#create', as: 'sessions'
  get 'signout' => 'sessions#destroy', as: 'signout'
  
  get 'signup' => 'users#new', as: 'signup'
  
  get '/authors' => 'users#authors', as: 'authors'
  
  get '/messages/:id/view' => 'messages#view', as: 'view_message'
  
  resources :users
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  
  resources :messages

end

app/views/layouts/_footer.html.erb
<footer id="footer-main">
  <div>
    <%= image_tag 'anvil.png' %>
    <section style="margin-top: -0.5em;">
      <ul>
        <li><%= link_to 'Our Community', users_path %></li>
        <li><%= link_to 'Our Authors', authors_path %></li>
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to 'Sign In', signin_path %></li>
      </ul>
    </section>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header-main">
  <div id="logo-container" class="clearfix">
    <%= link_to root_path, class: 'clearfix' do %>
      <!--<h1 id="giant-brand" class="">TheForge</h1>-->
      <%= image_tag 'logo.png', id: 'giant-brand' %>
    <% end %>
    <div id="menu-toggle">
      <%= image_tag 'menu-black.png', class: 'btn-nav' %>
    </div>
  </div>
  <nav id="nav-main">
    <ul class="clearfix">
      <li class="has-drop-nav">
        <%= link_to 'Posts', posts_path %>
      </li>
      
      <% if current_user.author %>
        <li class="has-drop-nav">
          <%= link_to 'New Post', new_post_path %>
        </li>
      <% end %>
      
      <li class="has-drop-nav">
        <% if signed_in? %>
          <%= link_to 'My Profile', current_user %>
          <ul class="drop-nav">
            <li class="last"><%= link_to 'Sign Out', signout_path %></li>
          </ul>
        <% else %>
          <%= link_to 'Sign In', signin_path %>
        <% end %>
      </li>
    </ul>
  </nav>

  <!--<form role="search" id="searchArea" class="search-area" method="get" action="http://www.harvard.edu/searches/">
    <label for="siteSearch">
      <span class="is-visually-hidden">
        Search:
      </span>
    </label>

    <input type="search" name="searchtext" id="searchSite" class="input-search" aria-label="search" placeholder="What can we help you find?">
    <button type="button" class="btn--mobile-site-search">
      <span class="is-visually-hidden">
        Open Search
      </span>
    </button>
  </form>-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheForge</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>
<body>
  <%= render 'layouts/header' %>
  
  <div id="wrapper">
    <section id="section-main">
      <%= yield %>
    </section>
    
    <%= yield :aside %>
  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>